[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asv_test"
version = "0.1.0"
description = "An empty project"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
requires-python = ">=3.12"